"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getWatchlist, setWatchlist } from "@/lib/watchlist";
const KEY = "market:thesis:TTWO:v1";
const CHECKS = ["שינוי במועד ההשקה", "עדכון הנחיית Net Bookings", "תזרים והוצאות לאחר ההשקה"];
type Note = { thesis:string; invalidation:string; checks:string[]; savedAt:string };
function readNote(): Note | null {
  try { const v:unknown=JSON.parse(localStorage.getItem(KEY)??"null"); if (!v || typeof v!=="object") return null; const n=v as Partial<Note>; return typeof n.thesis==="string" && typeof n.invalidation==="string" && typeof n.savedAt==="string" && Array.isArray(n.checks) ? {thesis:n.thesis.slice(0,1200),invalidation:n.invalidation.slice(0,1200),savedAt:n.savedAt,checks:n.checks.filter(c=>typeof c==="string" && CHECKS.includes(c))}:null; } catch {return null;}
}
export function ThesisNotebook({compact=false}:{compact?:boolean}) {
  const [thesis,setThesis]=useState(""); const [invalidation,setInvalidation]=useState(""); const [checks,setChecks]=useState<string[]>(CHECKS); const [saved,setSaved]=useState<string|null>(null); const [message,setMessage]=useState(""); const [dirty,setDirty]=useState(false);
  useEffect(()=>{const sync=()=>{const n=readNote();if(n){setThesis(n.thesis);setInvalidation(n.invalidation);setChecks(n.checks);setSaved(n.savedAt);}else{setSaved(null);}};sync();window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync);},[]);
  if(compact) return saved ? <aside className="saved-thesis"><span className="micro-label">YOUR RESEARCH / TTWO</span><h2>התזה ששמרת</h2><p>{thesis}</p><p><strong>מה ישנה את דעתי: </strong>{invalidation}</p><Link href="/launch/ttwo#my-thesis">לפתוח ולעדכן את התזה ←</Link></aside> : null;
  const save=()=>{try {const savedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify({thesis,invalidation,checks,savedAt}));setSaved(savedAt);setDirty(false);setWatchlist([...getWatchlist(),"TTWO"]);setMessage(getWatchlist().includes("TTWO")?"התזה נשמרה ו־TTWO נוספה למעקב בדפדפן הזה.":"התזה נשמרה. לא הצלחנו לעדכן את רשימת המעקב.");}catch{setMessage("הדפדפן לא מאפשר שמירה כרגע. הטקסט נשאר כאן — אפשר להעתיק אותו לפני היציאה.");}};
  return <section id="my-thesis" className="thesis-notebook" aria-labelledby="notebook-title"><div className="notebook-heading"><span className="micro-label">YOUR TURN / FROM THESIS TO MONITOR</span><h2 id="notebook-title">מה צריך לקרות כדי שתשתכנעו?</h2><p>תזה שימושית כוללת גם את הסיבה לשנות אותה. כתבו את שתיהן לפני העדכון הבא.</p></div><form onSubmit={e=>{e.preventDefault();save();}}><div className="notebook-fields"><label htmlFor="thesis-statement">התזה שלי<textarea id="thesis-statement" maxLength={1200} required minLength={10} rows={4} value={thesis} placeholder="אני בוחן/ת את TTWO כי…" onChange={e=>{setThesis(e.target.value);setDirty(true);setMessage("");}}/></label><label htmlFor="thesis-invalidation">מה ישנה את דעתי<textarea id="thesis-invalidation" maxLength={1200} required minLength={10} rows={4} value={invalidation} placeholder="אבדוק מחדש את ההנחה אם…" onChange={e=>{setInvalidation(e.target.value);setDirty(true);setMessage("");}}/></label></div><fieldset><legend>מה לבדוק בביקור הבא</legend>{CHECKS.map(check=><label key={check}><input type="checkbox" checked={checks.includes(check)} onChange={()=>{setChecks(previous=>previous.includes(check)?previous.filter(c=>c!==check):[...previous,check]);setDirty(true);setMessage("");}}/>{check}</label>)}</fieldset><div className="notebook-actions"><button type="submit" className="btn btn-primary">לשמור תזה ולהוסיף למעקב ←</button><Link href="/watchlist">לרשימת המעקב</Link>{saved && <span>{dirty?"יש שינויים שלא נשמרו":"נשמר בדפדפן"}</span>}</div><p role="status" className="notebook-status">{message}</p><small>שמירה מקומית בלבד. אינה מסונכרנת בין מכשירים ואינה מפעילה התראות. ניקוי נתוני הדפדפן ימחק את התזה.</small></form></section>;
}
